### PR TITLE
do not use container; image with ubuntu-20.04 already available on git…

### PR DESCRIPTION
**Pull request by SergeevPavel**
…hub actions

### CODE REVIEW

**Comment by SergeevPavel** [comment]
@igordmn sorry for bothering, but we still can't build it on linux-wasm
last try was:
```
Run sudo ./script/prepare_linux_wasm.sh
/__w/_temp/09bec703-8de6-4752-a523-b66e47c[1](https://github.com/JetBrains/skia-pack/runs/7886005903?check_suite_focus=true#step:4:1)59a8.sh: 1: sudo: not found
Error: Process completed with exit code 12[7](https://github.com/JetBrains/skia-pack/runs/7886005903?check_suite_focus=true#step:4:8).
```
maybe there is no `sudo` in container, so I move it out of docker

**Comment by igordmn** [comment]
In [the previous version](https://github.com/JetBrains/skia-pack/pull/15/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L107) there was no sudo. Maybe we just remove sudo?

Also, in the new version we don't clone emsdk and call emsdk_env. Is it not needed?

**Comment by eymar** [comment]
> In [the previous version](https://github.com/JetBrains/skia-pack/pull/15/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L107) there was no sudo. Maybe we just remove sudo?
> 
> Also, in the new version we don't clone emsdk and call emsdk_env. Is it not needed?

prepare_linux_wasm.sh needs to be pushed with chmod +x

plus it''s not complete at the moment?
emsdk has to be installed:? 
```
if [ -d ./emsdk ]; then
  cd ./emsdk
  git pull
else
  git clone https://github.com/emscripten-core/emsdk.git
  cd ./emsdk
fi
./emsdk install 2.0.29
./emsdk activate 2.0.29
source ./emsdk_env.sh
```

**Comment by SergeevPavel** [comment]
yes emsdk is installed and activated by `tools/git-sync-deps` now

**Pull request closed without merging**
